export const departments = [
    'engineering',
    'product',
    'marketing',
    'finance',
    'hr',
    'it',
    'sales',
    'academy',
    'legal',
    'development', 
    'support', 
    'design', 
    'management',
    'other',
]