export const weeklyData = [
    { day: "Monday", interactions: 186 },
    { day: "Tuesday", interactions: 305 },
    { day: "Wednesday", interactions: 237 },
    { day: "Thursday", interactions: 73 },
    { day: "Friday", interactions: 209 },
    { day: "Saturday", interactions: 214 },
]

export const DailyData = [
    { day: "1", interactions: 1 },
    { day: "2", interactions: 3 },
    { day: "3", interactions: 12 },
    { day: "4", interactions: 3 },
    { day: "5", interactions: 4 },
    { day: "6", interactions: 0 },
    { day: "7", interactions: 0 },
    { day: "8", interactions: 3 },
    { day: "9", interactions: 3 },
    { day: "10", interactions: 2 },
    { day: "11", interactions: 4 },
    { day: "12", interactions: 6 },
    { day: "13", interactions: 7 },
    { day: "14", interactions: 6 },
    { day: "15", interactions: 4 },
    { day: "16", interactions: 4 },
    { day: "17", interactions: 3 },
    { day: "18", interactions: 7 },
    { day: "19", interactions: 3 },
    { day: "20", interactions: 8 },
    { day: "21", interactions: 15 },
    { day: "22", interactions: 2 },
    { day: "23", interactions: 6 },
    { day: "24", interactions: 8 },
    { day: "25", interactions: 5 },
    { day: "26", interactions: 8 },
    { day: "27", interactions: 9 },
    { day: "28", interactions: 4 },
    { day: "29", interactions: 5 },
    { day: "30", interactions: 8 },
    { day: "31", interactions: 3 },
]